COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
#  SQLALCHEMY_DATABASE_URI: 'sqlite://'
#  SQLALCHEMY_DATABASE_URI: 'sqlite:///device_db.sqlite'
  SQLALCHEMY_DATABASE_URI: 'mysql://taras:t1a2r3a4s5$$@labs-cloud.mysql.database.azure.com:3306/flightradarlab3'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://taras:t1a2r3a4s5$$@labs-cloud.mysql.database.azure.com:3306/flightradarlab3'


ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: root
